/**
 * Practice Problems Data
 * 
 * This file contains all programming practice problems for C, C++, Java, and Python.
 * 
 * How to add a new problem:
 * 1. Add a new PracticeProblem object to the appropriate language array
 * 2. Ensure id is unique across all languages
 * 3. Use descriptive slug (kebab-case)
 * 4. Set appropriate difficulty, tags, and baseScore
 * 5. Provide realistic sample input/output
 * 
 * How to reset progress:
 * - Practice: localStorage.removeItem('csmStudyZonePracticeProgress')
 * - Contests: localStorage.removeItem('csmStudyZoneContestProgress')
 */

export type Language = 'C' | 'C++' | 'Java' | 'Python';

export type Difficulty = 'Beginner' | 'Intermediate' | 'Challenge';

export interface PracticeProblem {
  id: string;          // unique stable id
  slug: string;        // used inside URLs/fragments, e.g. 'sum-of-two-numbers'
  language: Language;
  title: string;
  tags: string[];      // ['Loops', 'Arrays']
  difficulty: Difficulty;
  description: string; // 2–4 line problem statement
  inputFormat: string;
  outputFormat: string;
  sampleInput: string;
  sampleOutput: string;
  constraints?: string;
  hint?: string;
  useCase: string;     // e.g. 'C Lab – loops and decision-making'
  externalCompilerUrl: string; // link to Programiz / JDoodle / OnlineGDB etc.
  baseScore: number;   // default points for solving (e.g. 10, 20, 30)
}

// Helper function to get all problems
export function getAllProblems(): PracticeProblem[] {
  return [...cProblems, ...cppProblems, ...javaProblems, ...pythonProblems];
}

// Helper function to get problem by id
export function getProblemById(id: string): PracticeProblem | undefined {
  return getAllProblems().find(p => p.id === id);
}

// Helper function to get problems by language
export function getProblemsByLanguage(language: Language): PracticeProblem[] {
  switch (language) {
    case 'C':
      return cProblems;
    case 'C++':
      return cppProblems;
    case 'Java':
      return javaProblems;
    case 'Python':
      return pythonProblems;
  }
}

// C Programming Problems
export const cProblems: PracticeProblem[] = [
  {
    id: 'c-001',
    slug: 'sum-of-two-numbers',
    language: 'C',
    title: 'Sum of Two Numbers',
    tags: ['Basic I/O', 'Arithmetic'],
    difficulty: 'Beginner',
    description: 'Write a C program to read two numbers from the user and print their sum.',
    inputFormat: 'Two integers separated by space.',
    outputFormat: 'Print the sum of the two numbers.',
    sampleInput: '10 20',
    sampleOutput: '30',
    constraints: '1 ≤ a, b ≤ 10^9',
    hint: 'Use scanf to read two integers and printf to display the sum.',
    useCase: 'C Programming Lab Experiment 1 – Basic I/O and Arithmetic. Essential for 1st year engineering practical exams.',
    externalCompilerUrl: 'https://www.programiz.com/c-programming/online-compiler/',
    baseScore: 10,
  },
  {
    id: 'c-002',
    slug: 'factorial-calculation',
    language: 'C',
    title: 'Factorial of a Number',
    tags: ['Loops', 'Recursion'],
    difficulty: 'Beginner',
    description: 'Write a C program to calculate the factorial of a given number using loops.',
    inputFormat: 'A single integer n.',
    outputFormat: 'Print the factorial of n.',
    sampleInput: '5',
    sampleOutput: '120',
    constraints: '0 ≤ n ≤ 12',
    hint: 'Initialize result to 1, then multiply by numbers from 1 to n in a loop.',
    useCase: 'C Programming Lab Experiment 3 – Factorial Calculation. Commonly asked in lab exams and viva.',
    externalCompilerUrl: 'https://www.programiz.com/c-programming/online-compiler/',
    baseScore: 15,
  },
  {
    id: 'c-003',
    slug: 'fibonacci-series',
    language: 'C',
    title: 'Fibonacci Series',
    tags: ['Loops', 'Sequences'],
    difficulty: 'Beginner',
    description: 'Write a C program to generate Fibonacci series up to n terms.',
    inputFormat: 'A single integer n (number of terms).',
    outputFormat: 'Print Fibonacci series with n terms separated by space.',
    sampleInput: '7',
    sampleOutput: '0 1 1 2 3 5 8',
    constraints: '1 ≤ n ≤ 20',
    hint: 'First two terms are 0 and 1. Each subsequent term is the sum of previous two terms.',
    useCase: 'C Programming Lab Experiment 9 – Fibonacci Using Recursion. Important for understanding loops and sequences.',
    externalCompilerUrl: 'https://www.programiz.com/c-programming/online-compiler/',
    baseScore: 15,
  },
  {
    id: 'c-004',
    slug: 'array-max-min',
    language: 'C',
    title: 'Find Maximum and Minimum in Array',
    tags: ['Arrays', 'Loops'],
    difficulty: 'Intermediate',
    description: 'Write a C program to find the maximum and minimum elements in an array.',
    inputFormat: 'First line: n (size of array). Second line: n integers separated by space.',
    outputFormat: 'Print maximum and minimum separated by space.',
    sampleInput: '5\n10 5 8 3 12',
    sampleOutput: '12 3',
    constraints: '1 ≤ n ≤ 100, -10^6 ≤ arr[i] ≤ 10^6',
    hint: 'Initialize max to first element and min to first element, then compare with all other elements.',
    useCase: 'C Programming Lab Experiment 6 – Array Statistics. Useful for 1st year engineering practical exams.',
    externalCompilerUrl: 'https://www.programiz.com/c-programming/online-compiler/',
    baseScore: 20,
  },
  {
    id: 'c-005',
    slug: 'matrix-addition',
    language: 'C',
    title: 'Matrix Addition',
    tags: ['2D Arrays', 'Nested Loops'],
    difficulty: 'Intermediate',
    description: 'Write a C program to add two matrices of the same size.',
    inputFormat: 'First line: rows and columns. Then elements of first matrix, then second matrix.',
    outputFormat: 'Print the sum matrix.',
    sampleInput: '2 2\n1 2\n3 4\n5 6\n7 8',
    sampleOutput: '6 8\n10 12',
    constraints: '1 ≤ rows, cols ≤ 10',
    hint: 'Use nested loops to add corresponding elements of both matrices.',
    useCase: 'C Programming Lab Experiment 7 – Matrix Operations. Essential for understanding 2D arrays.',
    externalCompilerUrl: 'https://www.programiz.com/c-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'c-006',
    slug: 'string-palindrome',
    language: 'C',
    title: 'Check if String is Palindrome',
    tags: ['Strings', 'Loops'],
    difficulty: 'Intermediate',
    description: 'Write a C program to check if a given string is a palindrome (reads same forwards and backwards).',
    inputFormat: 'A single string (without spaces).',
    outputFormat: 'Print "Palindrome" or "Not Palindrome".',
    sampleInput: 'madam',
    sampleOutput: 'Palindrome',
    constraints: '1 ≤ length ≤ 100',
    hint: 'Compare characters from start and end, moving towards center.',
    useCase: 'C Programming Lab Experiment 8 – String Operations. Commonly asked in lab exams.',
    externalCompilerUrl: 'https://www.programiz.com/c-programming/online-compiler/',
    baseScore: 20,
  },
  {
    id: 'c-007',
    slug: 'student-struct-record',
    language: 'C',
    title: 'Student Record Using Structures',
    tags: ['Structures', 'Input/Output'],
    difficulty: 'Intermediate',
    description: 'Write a C program to store and display student information (roll number, name, marks) using structures.',
    inputFormat: 'Roll number, name, and marks (float) separated by newlines.',
    outputFormat: 'Print student details in formatted manner.',
    sampleInput: '101\nJohn Doe\n85.5',
    sampleOutput: 'Roll: 101\nName: John Doe\nMarks: 85.50',
    constraints: 'Name length ≤ 50',
    hint: 'Define a structure with roll, name, and marks fields. Use scanf to read and printf to display.',
    useCase: 'C Programming Lab Experiment 11 – Structures Student Record. Important for understanding structures.',
    externalCompilerUrl: 'https://www.programiz.com/c-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'c-008',
    slug: 'file-io-character-count',
    language: 'C',
    title: 'Count Characters in File',
    tags: ['File Handling', 'I/O'],
    difficulty: 'Challenge',
    description: 'Write a C program to count the number of characters in a file.',
    inputFormat: 'Read from a file named "input.txt".',
    outputFormat: 'Print the total character count.',
    sampleInput: '(file content: "Hello World")',
    sampleOutput: '11',
    constraints: 'File size ≤ 10KB',
    hint: 'Use fopen to open file, fgetc in a loop to read characters, and fclose to close file.',
    useCase: 'C Programming Lab Experiment 12 – File Handling Student Records. Advanced file operations for practical exams.',
    externalCompilerUrl: 'https://www.programiz.com/c-programming/online-compiler/',
    baseScore: 30,
  },
  {
    id: 'c-009',
    slug: 'prime-number-check',
    language: 'C',
    title: 'Check Prime Number',
    tags: ['Loops', 'Conditionals'],
    difficulty: 'Beginner',
    description: 'Write a C program to check if a given number is prime.',
    inputFormat: 'A single integer n.',
    outputFormat: 'Print "Prime" or "Not Prime".',
    sampleInput: '17',
    sampleOutput: 'Prime',
    constraints: '2 ≤ n ≤ 10^6',
    hint: 'A prime number is divisible only by 1 and itself. Check divisibility from 2 to sqrt(n).',
    useCase: 'C Programming Lab Experiment 4 – Prime Number Check. Fundamental for understanding loops and conditions.',
    externalCompilerUrl: 'https://www.programiz.com/c-programming/online-compiler/',
    baseScore: 15,
  },
  {
    id: 'c-010',
    slug: 'array-reverse',
    language: 'C',
    title: 'Reverse an Array',
    tags: ['Arrays', 'Pointers'],
    difficulty: 'Intermediate',
    description: 'Write a C program to reverse an array using pointers.',
    inputFormat: 'First line: n (size). Second line: n integers.',
    outputFormat: 'Print reversed array.',
    sampleInput: '5\n1 2 3 4 5',
    sampleOutput: '5 4 3 2 1',
    constraints: '1 ≤ n ≤ 100',
    hint: 'Use two pointers, one at start and one at end, swap and move towards center.',
    useCase: 'C Programming Lab Experiment 10 – Array Reverse Using Pointers. Important for pointer operations.',
    externalCompilerUrl: 'https://www.programiz.com/c-programming/online-compiler/',
    baseScore: 25,
  },
];

// C++ Programming Problems
export const cppProblems: PracticeProblem[] = [
  {
    id: 'cpp-001',
    slug: 'sum-of-two-numbers-cpp',
    language: 'C++',
    title: 'Sum of Two Numbers',
    tags: ['Basic I/O', 'Arithmetic'],
    difficulty: 'Beginner',
    description: 'Write a C++ program to read two numbers and print their sum using cin and cout.',
    inputFormat: 'Two integers separated by space.',
    outputFormat: 'Print the sum.',
    sampleInput: '15 25',
    sampleOutput: '40',
    constraints: '1 ≤ a, b ≤ 10^9',
    hint: 'Use cin to read and cout to display. Similar to C but with different syntax.',
    useCase: 'C++ Programming Basics – Introduction to I/O. Essential for beginners learning C++.',
    externalCompilerUrl: 'https://www.programiz.com/cpp-programming/online-compiler/',
    baseScore: 10,
  },
  {
    id: 'cpp-002',
    slug: 'factorial-function',
    language: 'C++',
    title: 'Factorial Using Functions',
    tags: ['Functions', 'Loops'],
    difficulty: 'Beginner',
    description: 'Write a C++ program to calculate factorial using a separate function.',
    inputFormat: 'A single integer n.',
    outputFormat: 'Print the factorial.',
    sampleInput: '6',
    sampleOutput: '720',
    constraints: '0 ≤ n ≤ 12',
    hint: 'Create a function that takes n as parameter and returns factorial. Call it from main.',
    useCase: 'C++ Programming – Functions. Demonstrates function declaration, definition, and calling.',
    externalCompilerUrl: 'https://www.programiz.com/cpp-programming/online-compiler/',
    baseScore: 15,
  },
  {
    id: 'cpp-003',
    slug: 'complex-number-class',
    language: 'C++',
    title: 'Complex Number Addition Class',
    tags: ['Classes', 'OOP'],
    difficulty: 'Intermediate',
    description: 'Create a C++ class Complex with real and imaginary parts. Implement addition of two complex numbers.',
    inputFormat: 'Four floats: real1, imag1, real2, imag2.',
    outputFormat: 'Print sum in format: "a + bi".',
    sampleInput: '3 4\n1 2',
    sampleOutput: '4 + 6i',
    constraints: '-100 ≤ values ≤ 100',
    hint: 'Create a class with private members for real and imaginary. Use constructor and member function for addition.',
    useCase: 'C++ Programming – OOP Concepts. Essential for understanding classes and objects in C++.',
    externalCompilerUrl: 'https://www.programiz.com/cpp-programming/online-compiler/',
    baseScore: 30,
  },
  {
    id: 'cpp-004',
    slug: 'vector-operations',
    language: 'C++',
    title: 'Vector Operations',
    tags: ['STL', 'Vectors'],
    difficulty: 'Intermediate',
    description: 'Write a C++ program to perform basic vector operations: insert, erase, and find maximum element.',
    inputFormat: 'First line: n (size). Second line: n integers. Then operations.',
    outputFormat: 'Print vector after operations and maximum element.',
    sampleInput: '5\n1 2 3 4 5',
    sampleOutput: 'Maximum: 5',
    constraints: '1 ≤ n ≤ 100',
    hint: 'Use STL vector container. Include <vector> and <algorithm> headers.',
    useCase: 'C++ Programming – STL Overview. Important for understanding Standard Template Library.',
    externalCompilerUrl: 'https://www.programiz.com/cpp-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'cpp-005',
    slug: 'inheritance-shape',
    language: 'C++',
    title: 'Shape Class with Inheritance',
    tags: ['Inheritance', 'OOP'],
    difficulty: 'Challenge',
    description: 'Create a base class Shape and derived classes Circle and Rectangle. Calculate area using polymorphism.',
    inputFormat: 'Shape type and dimensions (radius for circle, length/width for rectangle).',
    outputFormat: 'Print the area.',
    sampleInput: 'Circle 5',
    sampleOutput: 'Area: 78.54',
    constraints: '1 ≤ dimensions ≤ 100',
    hint: 'Use virtual functions in base class. Override in derived classes. Use pointers for polymorphism.',
    useCase: 'C++ Programming – Inheritance and Polymorphism. Advanced OOP concepts for engineering students.',
    externalCompilerUrl: 'https://www.programiz.com/cpp-programming/online-compiler/',
    baseScore: 35,
  },
  {
    id: 'cpp-006',
    slug: 'string-manipulation',
    language: 'C++',
    title: 'String Manipulation',
    tags: ['Strings', 'STL'],
    difficulty: 'Beginner',
    description: 'Write a C++ program to reverse a string and check if it is palindrome using string class.',
    inputFormat: 'A single string.',
    outputFormat: 'Print reversed string and "Palindrome" or "Not Palindrome".',
    sampleInput: 'level',
    sampleOutput: 'level\nPalindrome',
    constraints: '1 ≤ length ≤ 100',
    hint: 'Use std::string class. Use reverse() from <algorithm> or manual reversal.',
    useCase: 'C++ Programming – Arrays & Strings. Basic string operations using STL.',
    externalCompilerUrl: 'https://www.programiz.com/cpp-programming/online-compiler/',
    baseScore: 20,
  },
  {
    id: 'cpp-007',
    slug: 'file-handling-cpp',
    language: 'C++',
    title: 'File Reading and Writing',
    tags: ['File Handling', 'I/O'],
    difficulty: 'Intermediate',
    description: 'Write a C++ program to read data from a file and write results to another file.',
    inputFormat: 'Read from "input.txt", write to "output.txt".',
    outputFormat: 'Process and write results to output file.',
    sampleInput: '(file: numbers 1 2 3 4 5)',
    sampleOutput: '(file: sum = 15)',
    constraints: 'File size ≤ 10KB',
    hint: 'Use ifstream for reading and ofstream for writing. Include <fstream> header.',
    useCase: 'C++ Programming – File Handling. Essential for file operations in C++.',
    externalCompilerUrl: 'https://www.programiz.com/cpp-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'cpp-008',
    slug: 'template-function',
    language: 'C++',
    title: 'Template Function for Maximum',
    tags: ['Templates', 'Generic Programming'],
    difficulty: 'Challenge',
    description: 'Write a C++ template function to find maximum of two numbers (works with int, float, double).',
    inputFormat: 'Two numbers (can be int or float).',
    outputFormat: 'Print the maximum.',
    sampleInput: '10.5 20.3',
    sampleOutput: '20.3',
    constraints: '-10^6 ≤ values ≤ 10^6',
    hint: 'Use template keyword. Function should work with any numeric type.',
    useCase: 'C++ Programming – Templates. Advanced feature for generic programming.',
    externalCompilerUrl: 'https://www.programiz.com/cpp-programming/online-compiler/',
    baseScore: 30,
  },
  {
    id: 'cpp-009',
    slug: 'exception-handling',
    language: 'C++',
    title: 'Exception Handling',
    tags: ['Exceptions', 'Error Handling'],
    difficulty: 'Intermediate',
    description: 'Write a C++ program to divide two numbers with exception handling for division by zero.',
    inputFormat: 'Two numbers a and b.',
    outputFormat: 'Print result or error message if b is zero.',
    sampleInput: '10 0',
    sampleOutput: 'Error: Division by zero!',
    constraints: '-1000 ≤ a, b ≤ 1000',
    hint: 'Use try-catch block. Throw exception when denominator is zero.',
    useCase: 'C++ Programming – Exception Handling. Important for robust error handling.',
    externalCompilerUrl: 'https://www.programiz.com/cpp-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'cpp-010',
    slug: 'operator-overloading',
    language: 'C++',
    title: 'Operator Overloading',
    tags: ['Operator Overloading', 'OOP'],
    difficulty: 'Challenge',
    description: 'Create a C++ class for 2D Point and overload + operator to add two points.',
    inputFormat: 'Four integers: x1, y1, x2, y2.',
    outputFormat: 'Print sum point coordinates.',
    sampleInput: '3 4\n1 2',
    sampleOutput: 'Point: (4, 6)',
    constraints: '-100 ≤ coordinates ≤ 100',
    hint: 'Define operator+ as member function or friend function. Return Point object.',
    useCase: 'C++ Programming – Operators. Advanced OOP concept for operator overloading.',
    externalCompilerUrl: 'https://www.programiz.com/cpp-programming/online-compiler/',
    baseScore: 35,
  },
];

// Java Programming Problems
export const javaProblems: PracticeProblem[] = [
  {
    id: 'java-001',
    slug: 'hello-world-class',
    language: 'Java',
    title: 'Hello World with Class',
    tags: ['Basic I/O', 'Classes'],
    difficulty: 'Beginner',
    description: 'Write a Java program to print "Hello, World!" using a class and main method.',
    inputFormat: 'No input.',
    outputFormat: 'Print "Hello, World!".',
    sampleInput: '',
    sampleOutput: 'Hello, World!',
    constraints: 'None',
    hint: 'Create a public class with public static void main method. Use System.out.println.',
    useCase: 'Java Programming – Introduction. First program for beginners learning Java.',
    externalCompilerUrl: 'https://www.programiz.com/java-programming/online-compiler/',
    baseScore: 10,
  },
  {
    id: 'java-002',
    slug: 'array-sum-java',
    language: 'Java',
    title: 'Sum of Array Elements',
    tags: ['Arrays', 'Loops'],
    difficulty: 'Beginner',
    description: 'Write a Java program to calculate the sum of all elements in an array.',
    inputFormat: 'First line: n (size). Second line: n integers.',
    outputFormat: 'Print the sum.',
    sampleInput: '5\n1 2 3 4 5',
    sampleOutput: '15',
    constraints: '1 ≤ n ≤ 100',
    hint: 'Use for loop to iterate through array and accumulate sum.',
    useCase: 'Java Programming – Arrays. Basic array operations for beginners.',
    externalCompilerUrl: 'https://www.programiz.com/java-programming/online-compiler/',
    baseScore: 15,
  },
  {
    id: 'java-003',
    slug: 'string-palindrome-java',
    language: 'Java',
    title: 'Palindrome String Check',
    tags: ['Strings', 'Methods'],
    difficulty: 'Intermediate',
    description: 'Write a Java program to check if a string is palindrome using String methods.',
    inputFormat: 'A single string.',
    outputFormat: 'Print "Palindrome" or "Not Palindrome".',
    sampleInput: 'racecar',
    sampleOutput: 'Palindrome',
    constraints: '1 ≤ length ≤ 100',
    hint: 'Use StringBuilder reverse() method or compare characters from both ends.',
    useCase: 'Java Programming – Arrays & Strings. String manipulation using Java String class.',
    externalCompilerUrl: 'https://www.programiz.com/java-programming/online-compiler/',
    baseScore: 20,
  },
  {
    id: 'java-004',
    slug: 'student-class-java',
    language: 'Java',
    title: 'Student Class with Methods',
    tags: ['Classes', 'OOP'],
    difficulty: 'Intermediate',
    description: 'Create a Java class Student with name, roll, and marks. Add methods to display and calculate grade.',
    inputFormat: 'Name, roll number, and marks.',
    outputFormat: 'Print student details and grade.',
    sampleInput: 'John\n101\n85',
    sampleOutput: 'Name: John\nRoll: 101\nMarks: 85\nGrade: A',
    constraints: 'Marks: 0-100',
    hint: 'Create class with private fields, constructor, getter methods, and grade calculation method.',
    useCase: 'Java Programming – OOP Concepts. Essential for understanding classes and objects in Java.',
    externalCompilerUrl: 'https://www.programiz.com/java-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'java-005',
    slug: 'inheritance-animal',
    language: 'Java',
    title: 'Animal Inheritance',
    tags: ['Inheritance', 'OOP'],
    difficulty: 'Intermediate',
    description: 'Create a base class Animal and derived classes Dog and Cat. Override makeSound() method.',
    inputFormat: 'Animal type (Dog or Cat).',
    outputFormat: 'Print the sound made by the animal.',
    sampleInput: 'Dog',
    sampleOutput: 'Woof!',
    constraints: 'None',
    hint: 'Use extends keyword for inheritance. Override makeSound() in derived classes.',
    useCase: 'Java Programming – Inheritance. Important OOP concept for understanding polymorphism.',
    externalCompilerUrl: 'https://www.programiz.com/java-programming/online-compiler/',
    baseScore: 30,
  },
  {
    id: 'java-006',
    slug: 'arraylist-operations',
    language: 'Java',
    title: 'ArrayList Operations',
    tags: ['Collections', 'ArrayList'],
    difficulty: 'Intermediate',
    description: 'Write a Java program to add, remove, and search elements in an ArrayList.',
    inputFormat: 'Operations: add, remove, search with values.',
    outputFormat: 'Print ArrayList after each operation.',
    sampleInput: 'add 10\nadd 20\nsearch 10',
    sampleOutput: 'Found at index: 0',
    constraints: '1 ≤ operations ≤ 50',
    hint: 'Use java.util.ArrayList. Use add(), remove(), and indexOf() methods.',
    useCase: 'Java Programming – Collections. Understanding ArrayList and collection framework.',
    externalCompilerUrl: 'https://www.programiz.com/java-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'java-007',
    slug: 'exception-handling-java',
    language: 'Java',
    title: 'Exception Handling',
    tags: ['Exceptions', 'Error Handling'],
    difficulty: 'Intermediate',
    description: 'Write a Java program to handle division by zero exception using try-catch.',
    inputFormat: 'Two integers a and b.',
    outputFormat: 'Print result or exception message.',
    sampleInput: '10 0',
    sampleOutput: 'Error: Division by zero!',
    constraints: '-1000 ≤ a, b ≤ 1000',
    hint: 'Use try-catch block. Catch ArithmeticException when dividing by zero.',
    useCase: 'Java Programming – Exception Handling. Essential for robust error handling in Java.',
    externalCompilerUrl: 'https://www.programiz.com/java-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'java-008',
    slug: 'file-io-java',
    language: 'Java',
    title: 'File Reading and Writing',
    tags: ['File Handling', 'I/O'],
    difficulty: 'Challenge',
    description: 'Write a Java program to read from a file and write to another file using FileReader and FileWriter.',
    inputFormat: 'Read from "input.txt".',
    outputFormat: 'Write processed data to "output.txt".',
    sampleInput: '(file: Hello World)',
    sampleOutput: '(file: HELLO WORLD)',
    constraints: 'File size ≤ 10KB',
    hint: 'Use FileReader/FileWriter or BufferedReader/BufferedWriter. Handle IOException.',
    useCase: 'Java Programming – File Handling. Important for file operations in Java applications.',
    externalCompilerUrl: 'https://www.programiz.com/java-programming/online-compiler/',
    baseScore: 30,
  },
  {
    id: 'java-009',
    slug: 'interface-shape',
    language: 'Java',
    title: 'Shape Interface',
    tags: ['Interfaces', 'OOP'],
    difficulty: 'Challenge',
    description: 'Create an interface Shape with calculateArea() method. Implement it in Circle and Rectangle classes.',
    inputFormat: 'Shape type and dimensions.',
    outputFormat: 'Print the area.',
    sampleInput: 'Circle 5',
    sampleOutput: 'Area: 78.54',
    constraints: '1 ≤ dimensions ≤ 100',
    hint: 'Define interface with calculateArea(). Implement in classes using implements keyword.',
    useCase: 'Java Programming – Interfaces. Advanced OOP concept for abstraction.',
    externalCompilerUrl: 'https://www.programiz.com/java-programming/online-compiler/',
    baseScore: 35,
  },
  {
    id: 'java-010',
    slug: 'multithreading-basics',
    language: 'Java',
    title: 'Basic Multithreading',
    tags: ['Multithreading', 'Threads'],
    difficulty: 'Challenge',
    description: 'Write a Java program to create two threads that print numbers alternately.',
    inputFormat: 'No input.',
    outputFormat: 'Print numbers from two threads alternately.',
    sampleInput: '',
    sampleOutput: 'Thread1: 1\nThread2: 2\nThread1: 3...',
    constraints: 'Print 1-10',
    hint: 'Extend Thread class or implement Runnable. Use synchronized or wait/notify for coordination.',
    useCase: 'Java Programming – Multithreading. Advanced topic for concurrent programming.',
    externalCompilerUrl: 'https://www.programiz.com/java-programming/online-compiler/',
    baseScore: 40,
  },
];

// Python Programming Problems
export const pythonProblems: PracticeProblem[] = [
  {
    id: 'python-001',
    slug: 'sum-of-two-numbers-python',
    language: 'Python',
    title: 'Sum of Two Numbers',
    tags: ['Basic I/O', 'Arithmetic'],
    difficulty: 'Beginner',
    description: 'Write a Python program to read two numbers and print their sum.',
    inputFormat: 'Two integers separated by space.',
    outputFormat: 'Print the sum.',
    sampleInput: '12 18',
    sampleOutput: '30',
    constraints: '1 ≤ a, b ≤ 10^9',
    hint: 'Use input() to read and split() to separate values. Convert to int.',
    useCase: 'Python Programming Basics – Introduction. First program for beginners learning Python.',
    externalCompilerUrl: 'https://www.programiz.com/python-programming/online-compiler/',
    baseScore: 10,
  },
  {
    id: 'python-002',
    slug: 'list-operations',
    language: 'Python',
    title: 'List Operations',
    tags: ['Lists', 'Data Structures'],
    difficulty: 'Beginner',
    description: 'Write a Python program to perform list operations: append, remove, and find maximum.',
    inputFormat: 'First line: n (size). Second line: n integers.',
    outputFormat: 'Print list after operations and maximum element.',
    sampleInput: '5\n1 2 3 4 5',
    sampleOutput: 'Maximum: 5',
    constraints: '1 ≤ n ≤ 100',
    hint: 'Use list methods: append(), remove(), and max() function.',
    useCase: 'Python Programming – Arrays & Strings. Basic list operations for beginners.',
    externalCompilerUrl: 'https://www.programiz.com/python-programming/online-compiler/',
    baseScore: 15,
  },
  {
    id: 'python-003',
    slug: 'dictionary-operations',
    language: 'Python',
    title: 'Dictionary Operations',
    tags: ['Dictionaries', 'Data Structures'],
    difficulty: 'Intermediate',
    description: 'Write a Python program to create a dictionary, add/update items, and search for a key.',
    inputFormat: 'Key-value pairs and a search key.',
    outputFormat: 'Print dictionary and search result.',
    sampleInput: 'name John\nage 20\nsearch name',
    sampleOutput: "Value: John",
    constraints: '1 ≤ pairs ≤ 50',
    hint: 'Use dict[key] = value to add/update. Use in operator or get() to search.',
    useCase: 'Python Programming – Data Structures. Understanding dictionaries and key-value pairs.',
    externalCompilerUrl: 'https://www.programiz.com/python-programming/online-compiler/',
    baseScore: 20,
  },
  {
    id: 'python-004',
    slug: 'function-factorial',
    language: 'Python',
    title: 'Factorial Using Function',
    tags: ['Functions', 'Recursion'],
    difficulty: 'Beginner',
    description: 'Write a Python function to calculate factorial of a number (both iterative and recursive).',
    inputFormat: 'A single integer n.',
    outputFormat: 'Print factorial.',
    sampleInput: '5',
    sampleOutput: '120',
    constraints: '0 ≤ n ≤ 20',
    hint: 'Define function with def keyword. Use loop for iterative or function call for recursive.',
    useCase: 'Python Programming – Functions. Understanding function definition and recursion.',
    externalCompilerUrl: 'https://www.programiz.com/python-programming/online-compiler/',
    baseScore: 15,
  },
  {
    id: 'python-005',
    slug: 'class-student',
    language: 'Python',
    title: 'Student Class',
    tags: ['Classes', 'OOP'],
    difficulty: 'Intermediate',
    description: 'Create a Python class Student with name, age, and marks. Add methods to display and calculate average.',
    inputFormat: 'Name, age, and list of marks.',
    outputFormat: 'Print student details and average marks.',
    sampleInput: 'John\n20\n85 90 88',
    sampleOutput: 'Name: John\nAge: 20\nAverage: 87.67',
    constraints: 'Marks: 0-100',
    hint: 'Use class keyword. Define __init__ for constructor and methods for operations.',
    useCase: 'Python Programming – OOP Concepts. Essential for understanding classes in Python.',
    externalCompilerUrl: 'https://www.programiz.com/python-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'python-006',
    slug: 'list-comprehension',
    language: 'Python',
    title: 'List Comprehension',
    tags: ['List Comprehension', 'Pythonic'],
    difficulty: 'Intermediate',
    description: 'Write a Python program to create a list of squares of even numbers using list comprehension.',
    inputFormat: 'A single integer n (upper limit).',
    outputFormat: 'Print list of squares of even numbers up to n.',
    sampleInput: '10',
    sampleOutput: '[4, 16, 36, 64, 100]',
    constraints: '1 ≤ n ≤ 100',
    hint: 'Use [x**2 for x in range(2, n+1, 2)] syntax for list comprehension.',
    useCase: 'Python Programming – Advanced Features. Pythonic way of creating lists.',
    externalCompilerUrl: 'https://www.programiz.com/python-programming/online-compiler/',
    baseScore: 20,
  },
  {
    id: 'python-007',
    slug: 'file-handling-python',
    language: 'Python',
    title: 'File Reading and Writing',
    tags: ['File Handling', 'I/O'],
    difficulty: 'Intermediate',
    description: 'Write a Python program to read from a file and write processed data to another file.',
    inputFormat: 'Read from "input.txt".',
    outputFormat: 'Write to "output.txt".',
    sampleInput: '(file: Python is great)',
    sampleOutput: '(file: PYTHON IS GREAT)',
    constraints: 'File size ≤ 10KB',
    hint: 'Use open() with "r" mode for reading and "w" mode for writing. Use with statement.',
    useCase: 'Python Programming – File Handling. Essential for file operations in Python.',
    externalCompilerUrl: 'https://www.programiz.com/python-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'python-008',
    slug: 'exception-handling-python',
    language: 'Python',
    title: 'Exception Handling',
    tags: ['Exceptions', 'Error Handling'],
    difficulty: 'Intermediate',
    description: 'Write a Python program to handle division by zero and invalid input exceptions.',
    inputFormat: 'Two numbers (can be invalid).',
    outputFormat: 'Print result or appropriate error message.',
    sampleInput: '10 0',
    sampleOutput: 'Error: Division by zero!',
    constraints: '-1000 ≤ values ≤ 1000',
    hint: 'Use try-except block. Catch ZeroDivisionError and ValueError.',
    useCase: 'Python Programming – Exception Handling. Important for robust error handling.',
    externalCompilerUrl: 'https://www.programiz.com/python-programming/online-compiler/',
    baseScore: 25,
  },
  {
    id: 'python-009',
    slug: 'dictionary-sorting',
    language: 'Python',
    title: 'Sort Dictionary by Values',
    tags: ['Dictionaries', 'Sorting'],
    difficulty: 'Challenge',
    description: 'Write a Python program to sort a dictionary by its values in descending order.',
    inputFormat: 'Dictionary with key-value pairs.',
    outputFormat: 'Print sorted dictionary.',
    sampleInput: '{"apple": 5, "banana": 2, "cherry": 8}',
    sampleOutput: 'cherry: 8, apple: 5, banana: 2',
    constraints: '1 ≤ pairs ≤ 50',
    hint: 'Use sorted() with key parameter. Use dict.items() and lambda function.',
    useCase: 'Python Programming – Advanced Data Structures. Dictionary manipulation and sorting.',
    externalCompilerUrl: 'https://www.programiz.com/python-programming/online-compiler/',
    baseScore: 30,
  },
  {
    id: 'python-010',
    slug: 'generator-fibonacci',
    language: 'Python',
    title: 'Fibonacci Generator',
    tags: ['Generators', 'Advanced'],
    difficulty: 'Challenge',
    description: 'Write a Python generator function to generate Fibonacci numbers up to n terms.',
    inputFormat: 'A single integer n.',
    outputFormat: 'Print Fibonacci sequence.',
    sampleInput: '8',
    sampleOutput: '0 1 1 2 3 5 8 13',
    constraints: '1 ≤ n ≤ 30',
    hint: 'Use yield keyword instead of return. Generator functions use less memory.',
    useCase: 'Python Programming – Generators. Advanced Python feature for memory-efficient sequences.',
    externalCompilerUrl: 'https://www.programiz.com/python-programming/online-compiler/',
    baseScore: 35,
  },
];

